import Head from 'next/head';

const Home = () => {
  return (
    <>
      <Head>
        <title>RESTful Countries</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    </>
  );
};

export default Home;
