import { useContext, useState, useEffect } from 'react';
import Head from 'next/head';
import Search from '../components/Search';
import Filter from '../components/Filter';
import Country from '../components/Country';
import CountriesContext from '../store/countries-context';

const Home = () => {
  const countriesCtx = useContext(CountriesContext);
  const { countries, filterCountries, getCountries } = countriesCtx;
  const [selected, setSelected] = useState('');

  // getCountries();

  useEffect(() => {
    // getCountries();
    filterCountries(selected)
  }, [selected]);

  const renderCountries = () => {
    // filterCountries(selected);
    return countries && countries.map(country => {
      return <Country country={country} key={country.name} />
    });
  };

  return (
    <>
      <Head>
        <title>RESTful Countries</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Search />

      <Filter 
        selected={selected}
        setSelected={setSelected}
      />

      <div>
        {renderCountries()}
      </div>
    </>
  );
};

export default Home;
