import { useContext } from 'react';
import Head from 'next/head';
import Search from '../components/Search';
import Filter from '../components/Filter';
import Country from '../components/Country';
import CountriesContext from '../store/countries-context';

const Home = () => {
  const countriesCtx = useContext(CountriesContext);
  const { countries, getRegions, filterCountries } = countriesCtx;
  const regions = getRegions();

  const renderCountries = countries && countries.map(country => {
    return (
      <Country country={country} key={country.name} />
    );
  });


  return (
    <>
      <Head>
        <title>RESTful Countries</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Search />
      <Filter 
        countries={countries} 
        filterCountries={filterCountries} 
        regions={regions}
      />

      <div>
        {renderCountries}
      </div>
    </>
  );
};

export default Home;
